export const GET_HOME_NAME='GET_HOME_NAME';
export const CHANGE_HOME_NAME='CHANGE_HOME_NAME';
export const GET_PRODUCTS_SUCCESS='GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_PENDING='GET_PRODUCTS_PENDING';
export const GET_PRODUCTS_ERROR='GET_PRODUCTS_ERROR';